name: Run Laravel Tests

on: [pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Clear config cache
        run: php artisan config:clear

      - name: Run Laravel Tests
        run: php artisan test
